routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});


/*********user routes************/
Route::get('/', 'Web@index');
Route::get('/faq', 'Web@faq');
Route::post('/store','Web@store')->name('store');
Route::post('/exchangeRate','Web@exchangeRate');
Route::post('/currency','Web@getCurrency');
Auth::routes(['verify' => true]);
Route::get('pmSuccess/{number}','Web@pmSuccess')->name('pmSuccess');
Route::match(['GET', 'POST'],'/pmCancel','Web@pmCancel')->name('pmCancel');
Route::post('/autoTransfer','Web@autoTransfer');
Route::post('autoTransferAdmin','Web@autoTransferAdmin');


// Route::post('/verifyUser','HomeController@verifyUser')->name('verify');
Route::get('/profile/{data?}','HomeController@profile')->name('profile');
Route::post('/profileupdate','HomeController@updateProfile')->name('profileupdate');
Route::resource('bitcoin', 'BitcoinPaymentController');

Route::post('/pmAlert','HomeController@pmAlert')->name('pmAlert');
Route::post('/ngnAutoFetch','HomeController@ngnAutoFetch')->name('ngnAutoFetch');
Route::post('/ngnAlert','HomeController@ngnAlert')->name('ngnAlert');
/*********user routes************/
    
Route::get('/home', 'HomeController@index')->name('home');
/*********Web Routes*************/
Route::group(['prefix'=>'home','as'=>'home.','middleware'=>'verified'],function(){
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::get('verify/{type}','BankDetails@verify')->name('verify');
    Route::post('verifyAmount','BankDetails@verifyAmount')->name('verifyAmount');
});
/*******************/


/*********Admin Routes**********/
Route::group(['prefix' => 'admin','as' => 'admin.','middleware'=>['auth','is_admin']], function () {
    Route::get('/home', 'HomeController@adminHome')->name('home');
	Route::resource('currency', 'CurrencyController');
	Route::resource('transaction', 'TransactionController');
    Route::resource('profile','SettingsController');
    Route::resource('exchange-rate','ExchangeRateController');
    Route::resource('users','Utills');
});
/*******************/


/**********Payment Routes**********/
Route::get('/payMoney/{amount}/{from_currency}/{to_currency}/{status}','RaveController@index')->name('payMoney');
Route::match(['GET', 'POST'], '/pay', 'RaveController@initialize')->name('pay');
Route::get('/rave/callback', 'RaveController@callback')->name('callback');

Route::match(['GET', 'POST'], '/btc', 'RaveController@raveBTC')->name('btc');
Route::post('/btcPayment', 'Utills@btcPayment')->name('btcPayment');
Route::post('/checkConfirmation', 'Utills@checkConfirmation')->name('checkConfirmation');
Route::get('/confirmationCallback', 'Utills@confirmationCallback')->name('confirmationCallback');
Route::post('/btcPendingPayment', 'Utills@btcPendingPayment')->name('btcPendingPayment');
Route::get('/pending', 'RaveController@pendingBTC')->name('pendingBTC');
Route::get('/btcCallback', 'RaveController@btcCallback')->name('btcCallback');
/********************/

resources/views/web/btc.blade.php
@extends('layouts.app')

@section('title') Pending Payment | {{ config('app.name','eCurrencyNG') }}  @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Payment Info') }}</div>
                <div class="card-body">
					<?php
                	$satoshi_amount = $amount / 100000000;
                	/*$now = Carbon::now();
    				$to = Carbon::parse('2020-8-1 00:00:00')->format('Y-m-d H:i:s');
    				$diff = $now->diffInHours($to);
    				echo $diff;die;*/
     //            	// $api = 'https://api.blockchain.info/merchant/6108261b-94a2-4603-b035-a61932383540/receive/new_address?password=Shreeji@1&second_password=&label=Order No : 1234';
     //            	$api = 'http://5ae6fed16122.ngrok.io/merchant/6108261b-94a2-4603-b035-a61932383540/new_address?password=Shreeji@1';
     //            	$client = new \GuzzleHttp\Client();
					// $response = $client->request('GET',$api);
					// $result = json_decode($response->getBody()->getContents());
					// $payTo = $result->address;
                	// $app_callback_url = URL::to("callback.php?invoice=".$orderID."&secret=".$secretKey);
                	// echo $app_callback_url;die;
					$app_receive_url = "https://api.blockchain.info/v2/receive?key=".$secretKey."&xpub=".$xpubKey."&callback=".urlencode($app_callback_url);					
                	if(isset($_SESSION['pay_address_ispaid']) && !(bool)$_SESSION['pay_address_ispaid']){
  						$payTo = $_SESSION['pay_address'];
					}else{
						/*$client = new \GuzzleHttp\Client();
						$response = $client->request('GET',$app_receive_url);
						$result = $response->getBody()->getContents();
						print_r($response);die;*/
					  $ch = curl_init();
					  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, true);
					  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
					  curl_setopt($ch, CURLOPT_URL, $app_receive_url);
					  $ccc = curl_exec($ch);
					  $json = json_decode($ccc, true);
					  
					  // print_r($json);die;
					  if(isset($payTo)){
						$chkAddress = DB::table('bitcoin_payments')->where('from_address',[$payTo])->first();
						session(['pay_address'=>$payTo]);//this can be added to the Database
						if(isset($chkAddress) && $chkAddress->status == "1"){
							session(['pay_address_ispaid'=>true]);//this can be read from the Database
						}else{
							session(['pay_address_ispaid'=>false]);//this can be read from the Database
						}
					  }else{
					  	return redirect()->back()->with('error',$json['message']);
					    // header('Location: error_page.php?msg='.$json['message']." - ".$json['description']);
					  }
					}
					?>
                	@push('scripts')
					<!-- TOASTR ALERT OPTIONAL -->
					<link href="{{ asset('assets/toastr/toastr.css') }}" rel="stylesheet">
					<link href="{{ asset('assets/example_1.css') }}" rel="stylesheet">
					<script src="{{ asset('assets/toastr/toastr.js') }}"></script>
                	<script>
						var btcs = new WebSocket('<?= $app_webSocketURL ?>');
						  console.log(btcs)

						btcs.onopen = function(){
						  btcs.send( JSON.stringify( {"op":"addr_sub", "addr":"<?= $payTo ?>"} ) );
						};
						btcs.onmessage = function(onmsg){
						  var response = JSON.parse(onmsg.data);
						  console.log(response)
						  var hash = response.x.hash;
						  var getOuts = response.x.out;
						  var countOuts = getOuts.length;
						  var getInputs = response.x.inputs;
						  var countInputs = getInputs.length;
						  for(var j = 0;j<countInputs;j++){
						  	var inputAdd = response.x.inputs[j].prev_out.addr;
						  	var receive_amount = response.x.inputs[j].prev_out.value;
						  	var inScript = response.x.inputs[j].prev_out.script;
						  }
						  for(var i = 0; i < countOuts; i++)
						  {
						      //check every output to see if it matches specified address
						      var outScript = response.x.out[i].script;
						      var outAdd = response.x.out[i].addr;
						      var specAdd = "<?= $payTo ?>";
						      var expectedAmnt = "<?= $satoshi_amount ?>";
						      if (outAdd == specAdd )
						      {
						        //var expectedAmnt = expectedval / 100000000;
						        var amount = response.x.out[i].value;
						        var calAmount = amount / 100000000;
						        //check if amount sent is equal to the expected
						        if(calAmount < expectedAmnt){
						          toastr.error("Received "+calAmount+" BTC amount was lower than the expected ");
						        }
						        	transactionInfo(outAdd,inputAdd,hash,outScript,calAmount);
						        	$('#messages').removeClass('text-info').addClass('text-success').html("<span class='text text-success'><i class='fa fa-thumbs-o-up'></i> Your payment of " + calAmount + " BTC has been Received </span>");
						        	//uses toastr/toastr.js and toastr/toastr.css
						        	toastr.success("Received " + calAmount + " BTC");

						        var beep_notify_sound = <?= $beed_notify ?>;
						        if(beep_notify_sound == true){
						         var snd = new  Audio("<?= $beed_sound_code ?>");  
						         snd.play();
						        }
						      } 
						  }
						}
						function transactionInfo(payto,payUser,hash,outScript,receive_amount){
							$.ajax({
								url:"{{ route('btcPendingPayment') }}",
								type:"POST",
								data:{payto:payto,payUser:payUser,hash:hash,script:outScript,receive_amount:receive_amount},
								beforeSend:function(){

								},
								success:function(response){
									console.log(response);
									alert(response.msg);
									if(response.success && response.success == "1"){
										window.location.href = response.redirect_url;
									}
								},
								error:function(error){
									console.log(error);
									toastr.error(error);
								}
							})
						}
						</script>
                	@endpush
                	@stack('scripts')
                	<!-- <div class="jumbotron">
					  <h1 class="text text-secondary text-center"><?= $amount ?> BTC</h1>
					</div> -->
					<div class="col-md-12">
					    <div class="offer offer-warning" id="Example2PaymentBox_<?= $orderID ?>">
					      <div class="shape">
					        <div class="shape-text">
					          BTC               
					        </div>
					      </div>
					      <div class="offer-content mt-3">
					        <h3 class="lead">
					          Send <b><?= $amount ?> BTC</b>
					        </h3>
					        <p>

					        <div class="col-sm-4 col-md-4 col-lg-4">
					          <img src="https://chart.googleapis.com/chart?chs=125x125&cht=qr&chl=bitcoin:<?= $payTo ?>?amount=<?= $amount ?>&choe=UTF-8"  class="img-responsive">
					        </div>
					        
					        <div class="col-sm-8 col-md-8 col-lg-8" style="padding:10px;">
					          Send <b><?= $amount ?> BTC</b><br/><input type="text" id="address_<?= $orderID ?>" class="form-control" value="<?= $payTo ?>" onclick="this.select();" readonly>
					          Simply scan QR Code with your mobile device or copy one in the input box<br/><br/>
					          <small class="text text-secondary" id="messages">
					          No need to refresh page, your payment status will be updated automatically.<br/>
					          <span class="text text-info"><i class="fa fa-spin fa-circle-o-notch"></i> Awaiting <?= $amount ?> bitcoin payment ....</span>
					          </small>
					        </div>
					        </p>
					      </div>
					    </div>
					</div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/web/faq.blade.php
@extends('layouts.layout')

@section('title') FAQ | {{ config('app.name', 'eCurrencyNG') }}  @endsection

@section('content')
<?php
$data = array(
	array('title'=>'Why use eCurrencyNG?','description'=>"Ecurrency is becoming more popular by the minute. It's starting to seem that everyone wants in, yet it isn't always so easy to get a hold of. For instance, the process of purchasing ecurrencies by bank transfer is a lengthy process that in some cases can take days, approving your documents can also take a while, so until you actually get your order processed it could take some time.Endopay is here to change that. We now offer the quickest way of purchasing ecurrency/crypto-currency online using your Credit Card, Debit Card or Cash, so you'll purchase your ecurrency within minutes!"),
	array('title'=>'What currencies does eCurrencyNG accept?','description'=>"We accept all Nigerian NGN,PM AND BTC at this time"),
	array('title'=>"How long does it take for eCurrencyNG to send my ecurrency once I've paid?",'description'=>"eCurrencyNG sends e-currency immediately after successful payment and wallet address have been confirmed (delays might occur in rear occasions)."),
	array('title'=>"Can I use a Credit/Debit Card?",'description'=>"Yes, you can purchase ecurrency with a Credit Card or a Debit Card via AccessBank / Interswitch, which allows you to pay online and receive your ecurrency quicker.(ONLY Nigerian Cards are currently acceptable.)"),
	array('title'=>"I am having issues paying with my Credit/Debit Card?",'description'=>"If you having paying with your credit/debit card, you can use your mobile/internet banking or cash deposit, quoting your order number as the reference.(NB. You can only pay for an order when it is valid, else charges may apply.)"),
	array('title'=>"Which ecurrencies are available to transfer proccess?",'description'=>"As for now we offer Bitcoin, Perfect Money And Nigeria."),
	array('title'=>"How can I prove that a transaction was made?",'description'=>"You can see in your account transaction section with your order id and transaction reference"),
	array('title'=>"Why must I provide my personal details?",'description'=>"As part of eCurrencyNG policy to prevent money laundering, we request our clients to identify themselves."),
	array('title'=>"Are my Credit/Debit Card details saved in your system?",'description'=>"As per government guide line and our privacy policy we can't store credit card and debit card details to our server."),
	array('title'=>"What are your fees?",'description'=>"All the fees depend on the transaction and depending on payment gateway rules."),
	array('title'=>'When can I get my eCurrencyNG tranfer amount?','description'=>"You can get within 30 minute after successful  transaction."),
);
?>
<div class="container">
	<div class="row justify-content-center mt-5 pt-5">
	    <div class="col-md-8">
			@foreach($data as $key=>$val)
			<div class="panel-group card" id="eCurrencyNG" data-toggle="collapse" data-parent="#eCurrencyNG" href = "#faq{{$key}}">
				   <div class = "panel panel-default">

				      <div class="card-header">
				         <h6 class="panel-title" data-toggle="collapse" data-parent="#eCurrencyNG" href = "#faq{{$key}}">
				         	{{ $val['title'] }}
				         	<button type="button" class="btn btn-default btn-sm pull-right" data-parent="#eCurrencyNG" data-toggle="collapse" data-target="#faq{{$key}}"><i class="fa fa-angle-down" aria-hidden="true"></i></button>
				         </h6>
				      </div>
				      
				      <div id = "faq{{$key}}" class="panel-collapse collapse">
				         <div class = "card-body">
				            {{ $val['description'] }}
				         </div>
				      </div>

				   </div>
			</div>
			@endforeach
		</div>
		</div>
</div>
@endsection

resources/views/web/home.blade.php
@extends('layouts.layout')

@section('title') Currency Exchange @endsection

@section('content')
	<!-- Breadcrumb Area Start -->
	<section class="breadcrumb-area extra-extra-padding">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<h4 class="title">
						Lend
					</h4>
					<ul class="breadcrumb-list">
						<li>
							<a href="index.html">
									<i class="fas fa-home"></i>
									Home
							</a>
						</li>
						<li>
							<span><i class="fas fa-chevron-right"></i> </span>
						</li>
						<li>
							<a href="borrow.html">Lend</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</section>
	<!-- Breadcrumb Area End -->

	<!-- calculator Area End -->
	<div class="calculator">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="calculator-box">
						<div class="row">
							<div class="col-lg-12">
								<form action="#" method="">
									@csrf
									<ul class="list">
										<li class="enter-amount">
											<label>Amount</label>
											<input type="text" value="" placeholder="Enter Amount">
										</li>
										<li class="from-currency">
											<label>From</label>
											<select name="from-currency" class="form-control" style="margin-top: 6px;">
												<option>-Select Any Currency-</option>
												<option value="PM">PM</option>
												<option value="BTC">BTC</option>
												<option value="Naira">Naira</option>
											</select>
										</li>
										<li class="to-currency">
											<label>To</label>
											<div class="form-group">
												<select name="to-currency" class="form-control" style="margin-top: 6px;">
													<option>-Select Any Currency-</option>
													<option value="PM">PM</option>
													<option value="BTC">BTC</option>
													<option value="Naira">Naira</option>
												</select>
											</div>
										</li>
										<li class="button">
											<button type="submit" name="submit" class="mybtn1">Get Started </button>
										</li>
									</ul>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- calculator Area End -->

	<!-- lend Area Start -->
	<section class="lend lend-page">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8 col-md-10">
					<div class="section-heading">
						<h5 class="subtitle extra-padding">
							The Most Trusted
						</h5>
						<h2 class="title extra-padding">
							Way to Lend
						</h2>
						<p class="text">
								Deposit crypto assets & earn interest on your reserves.
								Try to check out Lending Rate
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-12">
					<div class="responsive-table">
						<table class="table">
							<thead>
								<tr>
								<th scope="col">TOKEN NAME</th>
								<th scope="col">LEND APR</th>
								<th scope="col">BORROW APR</th>
								<th scope="col">LOANS ACTIVE</th>
								<th scope="col">RESERVE POOL</th>
								<th scope="col">LEND & EARN</th>
								</tr>
							</thead>
							<tbody>
								<tr>
								<td>
									<img src="assets/images/icon1.png" alt="">
									BTC
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
								<tr>
								<td>
									<img src="assets/images/icon2.png" alt="">
									ETH
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
								<tr>
								<td>
									<img src="assets/images/icon3.png" alt="">
									DASH
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
								<tr>
								<td>
									<img src="assets/images/icon4.png" alt="">
									ETC
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
								<tr>
								<td>
									<img src="assets/images/icon5.png" alt="">
									TRX
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
								<tr>
								<td>
									<img src="assets/images/icon1.png" alt="">
									BTC
								</td>
								<td>9.8%</td>
								<td>17.9%</td>
								<td>$325,650</td>
								<td>$481,694</td>
								<td>
									<a href="#">
										Lend
									</a>
								</td>
								</tr>
							</tbody>
							</table>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- lend Area End -->

	<!-- Get Start Area2 Start -->
	<section class="get-start2">
		<div class="container">
			<div class="row justify-content-center">
				<div class="col-lg-8 col-md-10">
					<div class="section-heading">
						<h5 class="subtitle">
							Get started
						</h5>
						<h2 class="title">
							In a few minutes
						</h2>
						<p class="text">
							Lendbo supports a variety of the most popular digital currencies.
							Deposit crypto assets & earn interest on your reserves.
						</p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-4">
					<div class="single-work">
						<div class="icon">
							<img src="assets/images/gs1.png" alt="">
						</div>
						<div class="content">
							<span class="num">01</span>
							<h4 class="title">
								Fund Account
							</h4>
							<p class="text">
								Signup and add crypto tokens to your smart account
 								to get started
							</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="single-work">
						<div class="icon">
							<img src="assets/images/gs2.png" alt="">
						</div>
						<div class="content">
							<span class="num">02</span>
							<h4 class="title">
								Create Reserve
							</h4>
							<p class="text">
								Signup and add crypto tokens to your smart account
 								to get started
							</p>
						</div>
					</div>
				</div>
				<div class="col-lg-4">
					<div class="single-work">
						<div class="icon">
							<img src="assets/images/gs3.png" alt="">
						</div>
						<div class="content">
							<span class="num">03</span>
							<h4 class="title">
								Earn Interest
							</h4>
							<p class="text">
								Signup and add crypto tokens to your smart account
 								to get started
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Get Start Area2 End -->

	<!-- Check Questions Area Start -->
	<section class="check-questions">
		<div class="container">
			<div class="row justify-content-between">
				<div class="col-lg-5 d-flex align-self-center">
					<div class="left-image">
						<img src="assets/images/cq-img.png" alt="">
					</div>
				</div>
				<div class="col-lg-6">
					<div class="rihgt-area">
						<div class="section-heading">
							<h5 class="subtitle extra-padding">
								If you have any
							</h5>
							<h2 class="title  extra-padding">
								Questions
							</h2>
							<p class="text">
								Our top priorities are to protect your privacy, 
								provide secure  transactions, and  safeguard your
								data. When you're ready to play, registering an
								account is required so we know you're of legal
								age and so no one else can use your account.We
								answer the most commonly asked questions
							</p>
							<a href="#" class="mybtn1">Check FAQs</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Check Questions Area End -->

	<!-- Get Start Area Start -->
	<section class="get-start">
		<div class="container">
			<div class="row">
				<div class="col-lg-5">
					<div class="left-image">
						<img src="assets/images/get-start.png" alt="">
					</div>
				</div>
				<div class="col-lg-7">
					<div class="rihgt-area">
						<div class="section-heading">
							<h5 class="subtitle extra-padding">
								Ready To Start
							</h5>
							<h2 class="title  extra-padding">
								Lending Or Borrowing
							</h2>
							<p class="text">
									What Are You Waiting For? Make Things Happen The Way
									You Want With Lendbo!
							</p>
							<a href="#" class="mybtn1">Get Started Today</a>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Get Start Area End -->
@endsection

resources/views/web/pm.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Transaction Alert') }}</div>
                <div class="card-body">
                	<p>Are You sure want to procced.?</p>
                	@php
                	$number = 'ecurrency'.\Str::random(20);
                	$admin = App\User::where('is_admin','1')->first();
                	@endphp
					<form action="https://perfectmoney.is/api/step1.asp" method="POST">
				        <p>
				          <input type="hidden" name="PAYEE_ACCOUNT" value="{{ $payee_account }}" />
				          <input type="hidden" name="PAYEE_NAME" value="{{ $payee_name }}" />
				          <input type="hidden" name="PAYMENT_AMOUNT" value="{{ $amount }}" />
				          <input type="hidden" name="PAYMENT_UNITS" value="USD" />
				          <input type="hidden" name="STATUS_URL" value="mailto:{{ $admin->email }}"/>
				          {{-- <input type="hidden" name="STATUS_URL" value="{{ url('/pmSuccess') }}"/> --}}
				          <input type="hidden" name="PAYMENT_URL" value="{{ url('/pmSuccess/'.$number) }}"/>
				          <input type="hidden" name="PAYMENT_URL_METHOD" value="GET" />
				          <input type="hidden" name="NOPAYMENT_URL" value="{{ url('/pmCancel') }}"/>
				          <input type="hidden" name="NOPAYMENT_URL_METHOD" value="GET" />
				          <input type="hidden" name="PAYMENT_ID" value="{{ $number }}"/>
				          <input type="hidden" name="SUGGESTED_MEMO" value="{{ $number }}">
				          <input type="hidden" name="SUGGESTED_MEMO_NOCHANGE" value="1">
				          <input type="submit" class="btn btn-primary" name="PAYMENT_METHOD" value="Procced"/>
				          <a href="{{ url('/') }}" name="cancel" class="btn btn-default">Cancel</a>
				        </p>
				    </form>
			  	</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/web/verify.blade.php
@extends('layouts.app')

@section('title') Verify | {{ config('app.name', 'eCurrencyNG') }}  @endsection

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @include('includes.flash')
            <div class="card">
                <div class="card-header">Verify amount</div>
                <form action="{{ route('home.verifyAmount') }}" method="POST">
                    @method('POST')
                    @csrf
                    <div class="card-body">
                        <p class="text-danger"></p>
                        <div class="form-group">
                            <label>Amount</label>
                            <input type="text" name="amount" value="" placeholder="Enter Amount" class="form-control">
                        </div>
                        <div class="form-group">
                            <input type="hidden" name="type" value="{{ Crypt::decrypt($type) }}">
                            <input type="submit" name="submit" value="Submit" class="btn btn-primary">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@endsection