routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});


/*********user routes************/
Route::get('/', 'Web@index');
Route::get('/faq', 'Web@faq');
Route::post('/store','Web@store')->name('store');
Route::post('/exchangeRate','Web@exchangeRate');
Route::post('/currency','Web@getCurrency');
Auth::routes(['verify' => true]);
Route::get('pmSuccess/{number}','Web@pmSuccess')->name('pmSuccess');
Route::match(['GET', 'POST'],'/pmCancel','Web@pmCancel')->name('pmCancel');
Route::post('/autoTransfer','Web@autoTransfer');
Route::post('autoTransferAdmin','Web@autoTransferAdmin');


// Route::post('/verifyUser','HomeController@verifyUser')->name('verify');
Route::get('/profile/{data?}','HomeController@profile')->name('profile');
Route::post('/profileupdate','HomeController@updateProfile')->name('profileupdate');
Route::resource('bitcoin', 'BitcoinPaymentController');

Route::post('/pmAlert','HomeController@pmAlert')->name('pmAlert');
Route::post('/ngnAutoFetch','HomeController@ngnAutoFetch')->name('ngnAutoFetch');
Route::post('/ngnAlert','HomeController@ngnAlert')->name('ngnAlert');
/*********user routes************/
    
Route::get('/home', 'HomeController@index')->name('home');
/*********Web Routes*************/
Route::group(['prefix'=>'home','as'=>'home.','middleware'=>'verified'],function(){
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::get('verify/{type}','BankDetails@verify')->name('verify');
    Route::post('verifyAmount','BankDetails@verifyAmount')->name('verifyAmount');
});
/*******************/


/*********Admin Routes**********/
Route::group(['prefix' => 'admin','as' => 'admin.','middleware'=>['auth','is_admin']], function () {
    Route::get('/home', 'HomeController@adminHome')->name('home');
	Route::resource('currency', 'CurrencyController');
	Route::resource('transaction', 'TransactionController');
    Route::resource('profile','SettingsController');
    Route::resource('exchange-rate','ExchangeRateController');
    Route::resource('users','Utills');
});
/*******************/


/**********Payment Routes**********/
Route::get('/payMoney/{amount}/{from_currency}/{to_currency}/{status}','RaveController@index')->name('payMoney');
Route::match(['GET', 'POST'], '/pay', 'RaveController@initialize')->name('pay');
Route::get('/rave/callback', 'RaveController@callback')->name('callback');

Route::match(['GET', 'POST'], '/btc', 'RaveController@raveBTC')->name('btc');
Route::post('/btcPayment', 'Utills@btcPayment')->name('btcPayment');
Route::post('/checkConfirmation', 'Utills@checkConfirmation')->name('checkConfirmation');
Route::get('/confirmationCallback', 'Utills@confirmationCallback')->name('confirmationCallback');
Route::post('/btcPendingPayment', 'Utills@btcPendingPayment')->name('btcPendingPayment');
Route::get('/pending', 'RaveController@pendingBTC')->name('pendingBTC');
Route::get('/btcCallback', 'RaveController@btcCallback')->name('btcCallback');
/********************/

app/Http/Controllers/TransactionController.php
<?php

namespace App\Http\Controllers;

use App\Transaction;
use Illuminate\Http\Request;

class TransactionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {  
        $data = Transaction::orderBy('id','desc')->with('user')->with('rave')->get();
        // echo "<pre>";print_r($data);die;
        return view('admin.transaction.index')->with('data',$data);
        // return response()->json($data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function edit(Transaction $transaction)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        if($request->status == "success"){
            if($transaction->status == 0){
                $res = Transaction::find($transaction->id)->update(['status'=>'1']);
                if($res){
                    return response()->json(
                        array(
                            'result' => $res,
                            'msg' => 'Status has been successfully approved',
                            'success' => '1',
                        )
                    );
                }else{
                    return response()->json(
                        array(
                            'result' => $res,
                            'msg' => 'Status has not been successfully changed',
                            'success' => '0',
                        )
                    );
                }
            }
        }else{
            $res = Transaction::find($transaction->id)->update(['status'=>'2']);
            if($res){
                return response()->json(
                    array(
                        'result' => $res,
                        'msg' => 'Status has been successfully rejected',
                        'success' => '0',
                    )
                );
            }else{
                return response()->json(
                    array(
                        'result' => $res,
                        'msg' => 'Something went wrong',
                        'success' => '0',
                    )
                );
            }
        }
        // echo $transaction->id;die;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Transaction $transaction)
    {
        $data = Transaction::findOrFail($transaction->id);
        $delete = $data->delete();
        if($delete){
            return redirect()->back()->with('success', 'Data deleted sucessfully!');
        }else{
            return redirect()->back()->with('error', 'Data not deleted sucessfully!');
        }
    }
}

resources/views/admin/transaction/index.blade.php
@extends('admin.layouts.layout')

@section('title') Transaction | {{ config('app.name', 'eCurrencyNG') }} @endsection

@section('content')
<div class="pcoded-content">
	<div class="pcoded-inner-content">
		@include('admin.includes.flash')
		<div class="card">
			<div class="card-header">
				<h5>Transaction List</h5>
				<span></span>
			</div>
			<div class="card-block">
				<div class="dt-responsive table-responsive">
					<!-- <a href="{{ route('admin.transaction.create') }}" class="btn btn-primary btn-sm pull-right">Add New<i
							class="ti-plus"></i></a> -->
					<table id="transactionTable" class="table table-striped table-bordered nowrap">
						<thead>
							<tr>
								<th>Sr No.</th>
								<th>Name</th>
								<th>Amount</th>
								<th>Transfer</th>
								<th>Txn Status</th>
								<th>Transfer Status</th>
								<th>Created At</th>
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@if(isset($data) && count($data) > 0)
								@foreach($data as $key=>$val)
									@if($val['rave']->txn_status == "1")
									<tr>
										<td>{{ $loop->iteration }}</td>
										<td>{{ $val["user"]->name }}</td>
										<td>{{ ($val->amount === "" ?? 0) - ($val["rave"]->charges === "" ?? 0 )." ".$val->from_currency }}</td>
										<td>{{ $val->transferAmount }} {{ $val->to_currency }}</td>
										<td>
											@if($val["rave"]->txn_status == "1") 
											<span class="label label-success">{{ __('Success') }}</span> 
											@else 
											<span class="label label-warning">{{ __('Pending') }}</span>
											@endif
										</td>
										<td>
											@csrf
											@if($val->status == "0")
												<span class="label label-warning">{{ __('Pending') }}</span>
												<!-- <button type="button" name="status" id="status" class="btn btn-warning btn-sm" data-id={{ $val->id }} data-value="{{ $val->status }}"><i class="ti-info"></i>{{ __('Pending') }}</button> -->
											@elseif($val->status == "1")
												<span class="label label-success">{{ __('Success') }}</span>
												<!-- <button type="button" name="status" id="status" class="btn btn-success btn-sm" data-id={{ $val->id }} data-value="{{ $val->status }}"><i class="ti-check"></i>{{ __('Success') }}</button> -->
											@else
												<span class="label label-danger">{{ __('Reject') }}</span>
												<!-- <button type="button" name="status" id="status" class="btn btn-danger btn-sm" data-id={{ $val->id }}  data-value="{{ $val->status }}"><i class="ti-close"></i>{{ __('Reject') }}</button> -->
											@endif
										</td>
										<td>{{ Carbon::parse($val->created_at)->format('Y-m-d h:i A') }}</td>
										<td>
											@if($val->status == "0")
												<button type="button" name="status" onclick="autoTransferAdmin(this);" class="btn btn-success btn-sm" data-to={{ $val->to_currency }} data-id={{ $val->id }}  data-value="{{ $val->status }}" data-status="success"><i class="ti-check"></i></button>
												<button type="button" name="status" id="reject" class="btn btn-danger btn-sm" data-id={{ $val->id }}  data-value="{{ $val->status }}" data-status="reject"><i class="ti-close"></i></button>
											@elseif($val->status == "1")
												<span class="label label-primary ">{{ __('Approved') }}</span>
											@else
												<span class="label label-danger">{{ __('Rejected') }}</span>
											@endif
										</td>
										<!-- <td>
											<a href="{{ route('admin.transaction.edit',$val['id']) }}"
												class="btn btn-info btn-sm"><i class="ti-pencil-alt"></i></a>
											<form id="delete-form" action="{{ route('admin.transaction.destroy',$val['id']) }}"
												method="POST">
												@method('DELETE')
												@csrf
												<button type="submit" name="delete" class="btn btn-danger btn-sm"><i
														class="ti-trash"></i></button>
											</form>
										</td> -->
									</tr>
									@endif
								@endforeach
							@else
								<tr>
									<td colspan="8" align="center">No Record Found</td>
								</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
@endsection