routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});


/*********user routes************/
Route::get('/', 'Web@index');
Route::get('/faq', 'Web@faq');
Route::post('/store','Web@store')->name('store');
Route::post('/exchangeRate','Web@exchangeRate');
Route::post('/currency','Web@getCurrency');
Auth::routes(['verify' => true]);
Route::get('pmSuccess/{number}','Web@pmSuccess')->name('pmSuccess');
Route::match(['GET', 'POST'],'/pmCancel','Web@pmCancel')->name('pmCancel');
Route::post('/autoTransfer','Web@autoTransfer');
Route::post('autoTransferAdmin','Web@autoTransferAdmin');


// Route::post('/verifyUser','HomeController@verifyUser')->name('verify');
Route::get('/profile/{data?}','HomeController@profile')->name('profile');
Route::post('/profileupdate','HomeController@updateProfile')->name('profileupdate');
Route::resource('bitcoin', 'BitcoinPaymentController');

Route::post('/pmAlert','HomeController@pmAlert')->name('pmAlert');
Route::post('/ngnAutoFetch','HomeController@ngnAutoFetch')->name('ngnAutoFetch');
Route::post('/ngnAlert','HomeController@ngnAlert')->name('ngnAlert');
/*********user routes************/
    
Route::get('/home', 'HomeController@index')->name('home');
/*********Web Routes*************/
Route::group(['prefix'=>'home','as'=>'home.','middleware'=>'verified'],function(){
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::get('verify/{type}','BankDetails@verify')->name('verify');
    Route::post('verifyAmount','BankDetails@verifyAmount')->name('verifyAmount');
});
/*******************/


/*********Admin Routes**********/
Route::group(['prefix' => 'admin','as' => 'admin.','middleware'=>['auth','is_admin']], function () {
    Route::get('/home', 'HomeController@adminHome')->name('home');
	Route::resource('currency', 'CurrencyController');
	Route::resource('transaction', 'TransactionController');
    Route::resource('profile','SettingsController');
    Route::resource('exchange-rate','ExchangeRateController');
    Route::resource('users','Utills');
});
/*******************/


/**********Payment Routes**********/
Route::get('/payMoney/{amount}/{from_currency}/{to_currency}/{status}','RaveController@index')->name('payMoney');
Route::match(['GET', 'POST'], '/pay', 'RaveController@initialize')->name('pay');
Route::get('/rave/callback', 'RaveController@callback')->name('callback');

Route::match(['GET', 'POST'], '/btc', 'RaveController@raveBTC')->name('btc');
Route::post('/btcPayment', 'Utills@btcPayment')->name('btcPayment');
Route::post('/checkConfirmation', 'Utills@checkConfirmation')->name('checkConfirmation');
Route::get('/confirmationCallback', 'Utills@confirmationCallback')->name('confirmationCallback');
Route::post('/btcPendingPayment', 'Utills@btcPendingPayment')->name('btcPendingPayment');
Route::get('/pending', 'RaveController@pendingBTC')->name('pendingBTC');
Route::get('/btcCallback', 'RaveController@btcCallback')->name('btcCallback');
/********************/

app/Currency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Currency extends Model
{
    //
	use SoftDeletes;
}

app/Http/Controllers/CurrencyController.php
<?php

namespace App\Http\Controllers;

use App\Currency;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class CurrencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $data = Currency::orderBy('id','desc')->get()->toArray();
        return view('admin.currency.index')->with('data',$data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.currency.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), [
           'name' => 'required',
           'value' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error',$validator->messages()->first());
        }
        $data = new Currency();
        $data->name = strtoupper($request->name);
        $data->value = $request->value;
        $data->save();
        return redirect()->route('admin.currency.index')->withInput()->with('success','Data saved successfully!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function show(Currency $currency)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function edit(Currency $currency)
    {
        return view('admin.currency.edit')->with('data',$currency);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Currency $currency)
    {
        // print_r($currency->toArray());die;
        // $data = Currency::findOrFail();
        $validator = Validator::make($request->all(), [
           'name' => 'required',
           'value' => 'required'
        ]);
        if ($validator->fails()) {
            return redirect()->back()->withInput()->with('error',$validator->messages()->first());
       }
       $data = new Currency;
       $data->name = strtoupper($request->name);
       $data->value = $request->value;
       Currency::where('id',$currency->id)->update($data->toArray());
       return redirect()->route('admin.currency.index')->withInput()->with('success','Data saved successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Currency  $currency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Currency $currency)
    {
        $data = Currency::findOrFail($currency->id);
        $delete = $data->delete();
        if($delete){
            return redirect()->back()->with('success', 'Data deleted sucessfully!');
        }else{
            return redirect()->back()->with('error', 'Data not deleted sucessfully!');
        }
    }
}

resources/views/admin/currency/create.blade.php
@extends('admin.layouts.layout')

@section('title') Currency | Crypto Exchange @endsection

@section('content')
<div class="pcoded-content">
	<div class="pcoded-inner-content">
		@include('admin.includes.flash')
		<div class="card">
			<div class="card-header">
				<h5>Add New Currency</h5>
				<span></span>
			</div>
			<form action="{{ route('admin.currency.store') }}" method="POST" name="currencyForm" id="currencyForm">
				@method('POST')
				@csrf
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<div class="form-group">
							<label>Name</label>
							<select class="form-control" name="name">
								<option value="">-Select Currency--</option>
								<option value="ngn">Nigiria</option>
								<option value="pm">PM</option>
								<option value="btc">BTC</option>
							</select>
						</div>
					</div>
					<div class="col-md-1"></div>
				</div>
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<div class="form-group">
							<label>Value</label>
							<input type="text" name="value" class="form-control" placeholder="Enter the value">
						</div>
					</div>
					<div class="col-md-1"></div>
				</div>
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<input type="submit" name="submit" value="Submit" class="btn btn-primary btn-sm">
					</div>
					<div class="col-md-1"></div>
				</div>
				<br>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/currency/edit.blade.php
@extends('admin.layouts.layout')

@section('title') Currency | Crypto Exchange @endsection

@section('content')
<div class="pcoded-content">
	<div class="pcoded-inner-content">
		@include('admin.includes.flash')
		<div class="card">
			<div class="card-header">
				<h5>Edit Currency</h5>
				<span></span>
			</div>
			<form action="{{ route('admin.currency.update',$data->id) }}" method="POST" name="currencyForm" id="currencyForm">
				@method('PUT')
				@csrf
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<div class="form-group">
							<label>Name</label>
							<select class="form-control" name="name" required>
								<option value="">-Select Currency--</option>
								<option value="naira" @if(strtolower($data->name) == "ngn") {{ __('selected') }} @endif>Nagiria
								</option>
								<option value="pm" @if(strtolower($data->name) == "pm") {{ __('selected') }} @endif>PM</option>
								<option value="btc" @if(strtolower($data->name) == "btc") {{ __('selected') }} @endif>BTC</option>
							</select>
						</div>
					</div>
					<div class="col-md-1"></div>
				</div>
				<!-- <div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<div class="form-group">
							<label>Value</label>
							<input type="text" name="value" class="form-control" value="{{ $data->value }}"
								placeholder="Enter the value" required>
						</div>
					</div>
					<div class="col-md-1"></div>
				</div> -->
				<div class="row">
					<div class="col-md-1"></div>
					<div class="col-md-10">
						<input type="submit" name="submit" value="Submit" class="btn btn-primary btn-sm">
					</div>
					<div class="col-md-1"></div>
				</div>
				<br>
			</form>
		</div>
	</div>
</div>
@endsection

resources/views/admin/currency/index.blade.php
@extends('admin.layouts.layout')

@section('title') Currency | {{ config('app.name', 'eCurrencyNG') }} @endsection

@section('content')
<div class="pcoded-content">
	<div class="pcoded-inner-content">
		@include('admin.includes.flash')
		<div class="card">
			<div class="card-header">
				<h5>Currency List</h5>
				<span></span>
			</div>
			<div class="card-block">
				<div class="dt-responsive table-responsive">
					{{-- <a href="{{ route('admin.currency.create') }}" class="btn btn-primary btn-sm pull-right">Add New<i
							class="ti-plus"></i></a> --}}
					<table id="currencyTable" class="table table-striped table-bordered nowrap">
						<thead>
							<tr>
								<th>Sr No.</th>
								<th>Name</th>
								<!-- <th>Value</th> -->
								<th>Action</th>
							</tr>
						</thead>
						<tbody>
							@if(isset($data) && count($data) > 0)
								@foreach($data as $key=>$val)
									<tr>
										<td>{{ $key+1 }}</td>
										<td>{{ $val["name"] }}</td>
										<td>
											<a href="{{ route('admin.currency.edit',$val['id']) }}"
												class="btn btn-info btn-sm"><i class="ti-pencil-alt"></i></a>
											<form id="delete-form" action="{{ route('admin.currency.destroy',$val['id']) }}"
												method="POST">
												@method('DELETE')
												@csrf
												<button type="submit" name="delete" class="btn btn-danger btn-sm"><i
														class="ti-trash"></i></button>
											</form>
										</td>
									</tr>
								@endforeach
							@else
								<tr>
									<td colspan="4" align="center">No Record Found</td>
								</tr>
							@endif
						</tbody>
					</table>
				</div>
			</div>
		</div>
@endsection