routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/clear-cache', function() {
    Artisan::call('cache:clear');
    Artisan::call('config:clear');
    Artisan::call('config:cache');
    return "Cache is cleared";
});


/*********user routes************/
Route::get('/', 'Web@index');
Route::get('/faq', 'Web@faq');
Route::post('/store','Web@store')->name('store');
Route::post('/exchangeRate','Web@exchangeRate');
Route::post('/currency','Web@getCurrency');
Auth::routes(['verify' => true]);
Route::get('pmSuccess/{number}','Web@pmSuccess')->name('pmSuccess');
Route::match(['GET', 'POST'],'/pmCancel','Web@pmCancel')->name('pmCancel');
Route::post('/autoTransfer','Web@autoTransfer');
Route::post('autoTransferAdmin','Web@autoTransferAdmin');


// Route::post('/verifyUser','HomeController@verifyUser')->name('verify');
Route::get('/profile/{data?}','HomeController@profile')->name('profile');
Route::post('/profileupdate','HomeController@updateProfile')->name('profileupdate');
Route::resource('bitcoin', 'BitcoinPaymentController');

Route::post('/pmAlert','HomeController@pmAlert')->name('pmAlert');
Route::post('/ngnAutoFetch','HomeController@ngnAutoFetch')->name('ngnAutoFetch');
Route::post('/ngnAlert','HomeController@ngnAlert')->name('ngnAlert');
/*********user routes************/
    
Route::get('/home', 'HomeController@index')->name('home');
/*********Web Routes*************/
Route::group(['prefix'=>'home','as'=>'home.','middleware'=>'verified'],function(){
    // Route::get('/home', 'HomeController@index')->name('home');
    Route::get('verify/{type}','BankDetails@verify')->name('verify');
    Route::post('verifyAmount','BankDetails@verifyAmount')->name('verifyAmount');
});
/*******************/


/*********Admin Routes**********/
Route::group(['prefix' => 'admin','as' => 'admin.','middleware'=>['auth','is_admin']], function () {
    Route::get('/home', 'HomeController@adminHome')->name('home');
	Route::resource('currency', 'CurrencyController');
	Route::resource('transaction', 'TransactionController');
    Route::resource('profile','SettingsController');
    Route::resource('exchange-rate','ExchangeRateController');
    Route::resource('users','Utills');
});
/*******************/


/**********Payment Routes**********/
Route::get('/payMoney/{amount}/{from_currency}/{to_currency}/{status}','RaveController@index')->name('payMoney');
Route::match(['GET', 'POST'], '/pay', 'RaveController@initialize')->name('pay');
Route::get('/rave/callback', 'RaveController@callback')->name('callback');

Route::match(['GET', 'POST'], '/btc', 'RaveController@raveBTC')->name('btc');
Route::post('/btcPayment', 'Utills@btcPayment')->name('btcPayment');
Route::post('/checkConfirmation', 'Utills@checkConfirmation')->name('checkConfirmation');
Route::get('/confirmationCallback', 'Utills@confirmationCallback')->name('confirmationCallback');
Route::post('/btcPendingPayment', 'Utills@btcPendingPayment')->name('btcPendingPayment');
Route::get('/pending', 'RaveController@pendingBTC')->name('pendingBTC');
Route::get('/btcCallback', 'RaveController@btcCallback')->name('btcCallback');
/********************/

resources/views/admin/includes/flash.blade.php
@if(Session::has('success'))
<div class="alert alert-success alert-block" style="background-color: #2ed8b6;border-color: #2ed8b6;color: #ffffff;">
	<button type="button" class="close" data-dismiss="alert" style="color: white;">×</button>
	{!! Session::get('success') !!}
</div>
@endif

@if(Session::has('error'))
<div class="alert alert-danger">
	<button type="button" class="close" data-dismiss="alert">×</button>
	{!! Session::get('error') !!}
</div>
@endif

resources/views/admin/includes/footer.blade.php
<script type="text/javascript">
	var base_url = '<?php echo URL::to('/'); ?>';
</script>
<script src="{{ asset('admin_assets/bower_components/jquery/js/jquery.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.min.js"></script>
<script src="{{ asset('admin_assets/bower_components/jquery-ui/js/jquery-ui.min.js') }}"></script>
<script src="{{ asset('admin_assets/bower_components/popper.js/js/popper.min.js') }}"></script>
<script src="{{ asset('admin_assets/bower_components/bootstrap/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin_assets/assets/pages/widget/excanvas.js') }}"></script>

<script src="{{ asset('admin_assets/bower_components/jquery-slimscroll/js/jquery.slimscroll.js') }}"></script>

<script src="{{ asset('admin_assets/bower_components/modernizr/js/modernizr.js') }}"></script>

<script src="{{ asset('admin_assets/assets/js/SmoothScroll.js') }}"></script>
<script src="{{ asset('admin_assets/assets/js/jquery.mCustomScrollbar.concat.min.js') }}"></script>

<script src="{{ asset('admin_assets/bower_components/chart.js/js/Chart.js') }}"></script>
<script src="{{ asset('admin_assets/assets/pages/widget/amchart/amcharts.js') }}"></script>
<script src="{{ asset('admin_assets/assets/pages/widget/amchart/serial.js') }}"></script>
<script src="{{ asset('admin_assets/assets/pages/widget/amchart/light.js') }}"></script>

<script src="{{ asset('admin_assets/assets/js/pcoded.min.js') }}"></script>
<script src="{{ asset('admin_assets/assets/js/dark-light/vertical-layout.min.js') }}"></script>

<script src="{{ asset('admin_assets/bower_components/datatables.net/js/jquery.dataTables.min.js') }}"></script>
<script src="{{ asset('admin_assets/bower_components/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
<script src="{{ asset('admin_assets/assets/js/toastr.min.js') }}"></script>
<script src="{{ asset('admin_assets/assets/js/custom.js') }}"></script>

<script src="{{ asset('admin_assets/assets/pages/dashboard/custom-dashboard.js') }}"></script>
<script src="{{ asset('admin_assets/assets/js/script.js') }}"></script>
</body>

</html>

resources/views/admin/includes/header.blade.php
<!DOCTYPE html>
<html lang="en">
<meta http-equiv="content-type" content="text/html;charset=UTF-8" />

<head>
    <title>@yield('title')</title>
    <meta name="csrf-token" content="{{ csrf_token() }}" />
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="description" content="" />
    <meta name="keywords" content="" />
    <meta name="author" content="" />
    <link rel="icon" href="http://html.codedthemes.com/gradient-able/files/assets/images/favicon.ico"
        type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600" rel="stylesheet">

    <link rel="stylesheet" type="text/css"
        href="{{ asset('admin_assets/bower_components/bootstrap/css/bootstrap.min.css') }}">

    <link rel="stylesheet" type="text/css"
        href="{{ asset('admin_assets/assets/icon/themify-icons/themify-icons.css') }}">

    <link rel="stylesheet" type="text/css"
        href="{{ asset('admin_assets/assets/icon/font-awesome/css/font-awesome.min.css') }}">

    <link rel="stylesheet" type="text/css" href="{{ asset('admin_assets/assets/css/jquery.mCustomScrollbar.css') }}">

    <link rel="stylesheet" href="{{ asset('admin_assets/assets/pages/chart/radial/css/radial.css') }}" type="text/css"
        media="all">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('admin_assets/bower_components/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" type="text/css"
        href="{{ asset('admin_assets/assets/css/toastr.min.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('admin_assets/assets/css/style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ asset('admin_assets/assets/css/custom.css') }}">
</head>

<body>
    <div class="theme-loader">
        <div class="loader-track">
            <div class="loader-bar"></div>
        </div>
    </div>

    <div class="" id="main_loader" style="display: none;flex-direction: column;justify-content: center;align-items: center;z-index: 11111111111;position: fixed;top: 0;right: 0;left: 0;bottom:0;width:100%;height:100%;background-color:#00000050;">
        <img src="{{ asset('assets/images/preloader.gif') }}" style="width: 25%;filter: hue-rotate(200deg);">
    </div>

    <div id="pcoded" class="pcoded">
        <div class="pcoded-overlay-box"></div>
        <div class="pcoded-container navbar-wrapper">
            <nav class="navbar header-navbar pcoded-header">
                <div class="navbar-wrapper">
                    <div class="navbar-logo">
                        <a class="mobile-menu" id="mobile-collapse" href="javascript:void(0);">
                            <i class="ti-menu"></i>
                        </a>
                        <div class="mobile-search">
                            <div class="header-search">
                                <div class="main-search morphsearch-search">
                                    <div class="input-group">
                                        <span class="input-group-addon search-close"><i class="ti-close"></i></span>
                                        <input type="text" class="form-control" placeholder="Enter Keyword">
                                        <span class="input-group-addon search-btn"><i class="ti-search"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{{ route('admin.home') }}">
                            <!-- <img class="img-fluid" src="{{ asset('admin_assets/assets/images/logo.png') }}"
                                alt="Theme-Logo" /> -->
                            <p style="font-size: 15px;">{{ config('app.name', 'eCurrency NG') }}</p>
                        </a>
                        <a class="mobile-options">
                            <i class="ti-more"></i>
                        </a>
                    </div>
                    <div class="navbar-container container-fluid">
                        <ul class="nav-left">
                            <li>
                                <div class="sidebar_toggle"><a href="javascript:void(0)"><i class="ti-menu"></i></a>
                                </div>
                            </li>
                            <!-- <li class="header-search">
                                <div class="main-search morphsearch-search">
                                    <div class="input-group">
                                        <span class="input-group-addon search-close"><i class="ti-close"></i></span>
                                        <input type="text" class="form-control">
                                        <span class="input-group-addon search-btn"><i class="ti-search"></i></span>
                                    </div>
                                </div>
                            </li> -->
                            <li>
                                <a href="javascript:void(0);" onclick="javascript:toggleFullScreen()">
                                    <i class="ti-fullscreen"></i>
                                </a>
                            </li>
                        </ul>
                        <ul class="nav-right">
                            <!-- <li class="header-notification">
                                <a href="javascript:void(0);">
                                    <i class="ti-bell"></i>
                                    <span class="badge bg-c-pink"></span>
                                </a>
                                <ul class="show-notification">
                                    <li>
                                        <h6>Notifications</h6>
                                        <label class="label label-danger">New</label>
                                    </li>
                                    <li>
                                        <div class="media">
                                            Coming Soon
                                            <img class="d-flex align-self-center img-radius"
                                                src="{{ asset('admin_assets/assets/images/avatar-2.jpg') }}"
                                                alt="Generic placeholder image">
                                            <div class="media-body">
                                                <h5 class="notification-user">{{ Auth::user()->name }}</h5>
                                                <p class="notification-msg">Lorem ipsum dolor sit amet, consectetuer
                                                    elit.</p>
                                                <span class="notification-time">30 minutes ago</span>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </li> -->
                            <li class="user-profile header-notification">
                                <a href="javascript:void(0);">
                                    <img src="{{ asset('admin_assets/assets/images/avatar-4.jpg') }}" class="img-radius"
                                        alt="User-Profile-Image">
                                    <span>{{ Auth::user()->name }}</span>
                                    <i class="ti-angle-down"></i>
                                </a>
                                <ul class="show-notification profile-notification">
                                    {{-- <li>
                                        <a href="#!">
                                            <i class="ti-settings"></i> Settings
                                        </a>
                                    </li> --}}
                                    <li>
                                        <a href="{{ route('admin.profile.index') }}">
                                            <i class="ti-user"></i> Profile
                                        </a>
                                    </li>
                                    {{-- <li>
                                        <a href="email-inbox.html">
                                            <i class="ti-email"></i> My Messages
                                        </a>
                                    </li>
                                    <li>
                                        <a href="auth-lock-screen.html">
                                            <i class="ti-lock"></i> Lock Screen
                                        </a>
                                    </li> --}}
                                    <li>
                                        <a href="{{ route('logout') }}"
                                            onclick="event.preventDefault();document.getElementById('logout-form').submit();"><i
                                                class="ti-layout-sidebar-left"></i>{{ __('Logout') }}</a>
                                        <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                            style="display: none;">
                                            @csrf
                                        </form>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

resources/views/admin/includes/sidebar.blade.php
<div class="pcoded-main-container">
	<div class="pcoded-wrapper">
		<nav class="pcoded-navbar">
			<div class="sidebar_toggle"><a href="javascript:void(0)"><i class="icon-close icons"></i></a></div>
			<div class="pcoded-inner-navbar main-menu">
				<div class="pcoded-navigation-label"></div>
				<ul class="pcoded-item pcoded-left-item">
					<!-- <li class="pcoded-hasmenu active pcoded-trigger tab"> -->
					<li class="tab">
						<a href="{{ route('admin.home') }}">
							<span class="pcoded-micon"><i class="ti-home"></i><b>D</b></span>
							<span class="pcoded-mtext">Dashboard</span>
							<span class="pcoded-mcaret"></span>
						</a>
						<!-- <ul class="pcoded-submenu">
							<li class="active">
								<a href="index-2.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Default</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class="">
								<a href="dashboard-ecommerce.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Ecommerce</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class=" ">
								<a href="dashboard-analytics.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Analytics</span>
									<span class="pcoded-badge label label-info ">NEW</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
						</ul> -->
					</li>

					<li class="tab">
						<a href="{{ route('admin.currency.index') }}">
							<span class="pcoded-micon"><i class="ti-money"></i><b>N</b></span>
							<span class="pcoded-mtext">Currency</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>

					<li class="tab bankInfo">
						<a href="{{ route('admin.users.index') }}">
							<span class="pcoded-micon"><i class="ti-user"></i><b>N</b></span>
							<span class="pcoded-mtext">Users</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>

					<li class="tab">
						<a href="{{ route('admin.transaction.index') }}">
							<span class="pcoded-micon"><i class="ti-location-arrow"></i><b>N</b></span>
							<span class="pcoded-mtext">Transactions</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>

					<li class="tab bankInfo">
						<a href="{{ route('admin.exchange-rate.index') }}">
							<span class="pcoded-micon"><i class="ti-wallet"></i><b>N</b></span>
							<span class="pcoded-mtext">Exchange Rate</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>

					<li class="tab bankInfo">
						<a href="{{ route('admin.profile.index') }}">
							<span class="pcoded-micon"><i class="ti-info-alt"></i><b>N</b></span>
							<span class="pcoded-mtext">Bank Details</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>

					<!-- <li class="pcoded-hasmenu">
						<a href="javascript:void(0)">
							<span class="pcoded-micon"><i class="ti-layout"></i><b>P</b></span>
							<span class="pcoded-mtext">Page layouts</span>
							<span class="pcoded-badge label label-warning">NEW</span>
							<span class="pcoded-mcaret"></span>
						</a>
						<ul class="pcoded-submenu">
							<li class=" pcoded-hasmenu">
								<a href="javascript:void(0)">
									<span class="pcoded-micon"><i class="icon-pie-chart"></i></span>
									<span class="pcoded-mtext">Vertical</span>
									<span class="pcoded-mcaret"></span>
								</a>
								<ul class="pcoded-submenu">
									<li class=" ">
										<a href="menu-static.html">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Static Layout</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-header-fixed.html">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Header Fixed</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-compact.html">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Compact</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-sidebar.html">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Sidebar Fixed</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
								</ul>
							</li>
							<li class=" pcoded-hasmenu">
								<a href="javascript:void(0)">
									<span class="pcoded-micon"><i class="icon-pie-chart"></i></span>
									<span class="pcoded-mtext">Horizontal</span>
									<span class="pcoded-mcaret"></span>
								</a>
								<ul class="pcoded-submenu">
									<li class=" ">
										<a href="menu-horizontal-static.html" target="_blank">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Static Layout</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-horizontal-fixed.html" target="_blank">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Fixed layout</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-horizontal-icon.html" target="_blank">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Static With Icon</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
									<li class=" ">
										<a href="menu-horizontal-icon-fixed.html" target="_blank">
											<span class="pcoded-micon"><i class="icon-chart"></i></span>
											<span class="pcoded-mtext">Fixed With Icon</span>
											<span class="pcoded-mcaret"></span>
										</a>
									</li>
								</ul>
							</li>
							<li class=" ">
								<a href="menu-bottom.html">
									<span class="pcoded-micon"><i class="icon-pie-chart"></i></span>
									<span class="pcoded-mtext">Bottom Menu</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class=" ">
								<a href="box-layout.html" target="_blank">
									<span class="pcoded-micon"><i class="icon-pie-chart"></i></span>
									<span class="pcoded-mtext">Box Layout</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class=" ">
								<a href="menu-rtl.html" target="_blank">
									<span class="pcoded-micon"><i class="icon-pie-chart"></i></span>
									<span class="pcoded-mtext">RTL</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
						</ul>
					</li>
					<li class="">
						<a href="navbar-light.html">
							<span class="pcoded-micon"><i class="ti-layout-cta-right"></i><b>N</b></span>
							<span class="pcoded-mtext">Navigation</span>
							<span class="pcoded-mcaret"></span>
						</a>
					</li>
					<li class="pcoded-hasmenu">
						<a href="javascript:void(0)">
							<span class="pcoded-micon"><i class="ti-view-grid"></i><b>W</b></span>
							<span class="pcoded-mtext">Widget</span>
							<span class="pcoded-badge label label-danger">100+</span>
							<span class="pcoded-mcaret"></span>
						</a>
						<ul class="pcoded-submenu">
							<li class="">
								<a href="widget-statistic.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Statistic</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class=" ">
								<a href="widget-data.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Data</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
							<li class=" ">
								<a href="widget-chart.html">
									<span class="pcoded-micon"><i class="ti-angle-right"></i></span>
									<span class="pcoded-mtext">Chart Widget</span>
									<span class="pcoded-mcaret"></span>
								</a>
							</li>
						</ul>
					</li> -->
				</ul>
		</nav>